{
  "process_id": "be9ce63b-6be7-408c-aa4e-3a0fcb68b9fd",
  "status": "IN_PROGRESS",
  "step_number": 2,
  "total_steps": 76,
  "step_message": "Reconcile and promote",
  "creation_time": "2023-08-03T13:10:02.287Z",
  "tenant_id": "0ced05a5f20a6e56abc1f9f165da63ad",
  "heartbeat_time": "2023-08-03T13:10:03.240Z",
  "messages": {
    "resources": [],
    "offset": 0,
    "set_uri": false,
    "limit": 10,
    "count": 0
  }
}
